#ifndef SR_MECANUM_PID_CORE_H
#define SR_MECANUM_PID_CORE_H


#include "ros/ros.h"
#include "ros/time.h"

// Here we include the message files. Autogenerated from the msg/ directory
#include <mecanum_msgs/PID.h>

#include <dynamic_reconfigure/server.h>
// Auto-generated from cfg/ directory.
#include <mecanum_pid/mecanumPIDConfig.h>

class MecanumPID
{
public:
  MecanumPID();
  ~MecanumPID();
  void configCallback(mecanum_pid::mecanumPIDConfig &config,double level);
  void publishMessage(ros::Publisher *pub_message);
  void messageCallback(const mecanum_msgs::PID::ConstPtr &msg);

  double p_;
  double d_;
  double i_;




};
#endif
